### ISSUE TITLE
Redundant text wrapping code for hints.

### ISSUE THREAD

**Issue by jhcole** [Purdue-EBEC/generic-grader#38]
`TextWrapper` instances are scattered throughout the different test types.  Each of them using the same formatting.  This should be handled in one place.  Possibly a `format_error` helper in utils that could take the error message, hint, IO log, and anything else we need as arguments.  This would also move the format_log code out of the User class so that all the formatting is handled in a single location.

**Comment by jscarfo11** [comment]
The text wrapping part of this was fixed by #86, however the rest of this issue will need to be refactored after the security fix detailed in #98
